#!/bin/sh -e

# Partial output from rules will never be accepted and must be rebuilt

assert-fail EXIT_CODE=1 numake
assert '[ -f dependency ]'
assert '[ ! -f all ]'
assert '[ -f rebuilt ]'

# Even if the target exists, it must still be rebuilt
rm -rf rebuilt
assert '[ -f dependency ]'
assert-fail EXIT_CODE=1 numake
assert '[ -f dependency ]'
assert '[ ! -f all ]'
assert '[ -f rebuilt ]'

# Only when the build script finishes successfully, it won't be rebuilt
rm -rf rebuilt
assert '[ -f dependency ]'
assert EXIT_CODE=0 numake
assert '[ -f all ]'
assert '[ -f dependency ]'
assert '[ -f rebuilt ]'

rm -rf rebuilt
assert EXIT_CODE=0 numake # If EXIT_CODE changes, target will be rebuilt so we keep it
assert '[ -f dependency ]'
assert '[ ! -f rebuilt ]'

# Fail the build again
assert-fail EXIT_CODE=1 numake
assert '[ -f dependency ]'
assert '[ -f rebuilt ]'

assert-fail EXIT_CODE=1 numake
assert '[ -f dependency ]'
assert '[ -f rebuilt ]'
