#!/bin/sh -e

# Verify the behaviour of order-only dependency: must be kept up-to-date but
# changes do not trigger a rebuild of targets which depend on it

assert numake

assert '[ -f rebuilt-all ]'
assert '[ -f rebuilt-order-only-dep ]'

# An order-only dependency must be kept up-to-date but does not trigger a rebuild
rm -rf rebuilt-*
echo new > dep
assert numake

assert '[ ! -f rebuilt-all ]'
assert '[ -f rebuilt-order-only-dep ]'

rm -rf rebuilt-*
echo new > dep
assert numake

assert '[ ! -f rebuilt-all ]'
assert '[ ! -f rebuilt-order-only-dep ]'
