#!/bin/sh -e

# Verify variable substitution and scoping rules

numake

assert '[ -f all ]'
assert '[ -f abcd-efgh ]'
assert '[ -f abcd ]'

assert-equal 'default_val' '`cat all`'
assert-equal 'default2_val' '`cat abcd`'
assert-equal '' '`cat abcd-efgh`'
assert-equal 'outer' '`cat scoped`'
assert-equal 'inner' '`cat inner`'
assert-equal 'aye' '`cat check-pwd`'

default=changed default2=changed2 numake
assert-equal 'changed' '`cat all`'
assert-equal 'changed2' '`cat abcd`'
assert-equal '' '`cat abcd-efgh`'
assert-equal 'inner' '`cat inner`'
assert-equal 'aye' '`cat check-pwd`'

numake check-consistency
numake check-consistency2

numake check-consistency var2=def
numake check-consistency2 var2=def

numake check-consistency var3=watwat
numake check-consistency2 var3=watwat

numake check-consistency var2=yay var3=nah
numake check-consistency2 var2=yay var3=nah

numake check-param var5=wat
