#!/bin/sh -e

numake

assert '[ -f all ]'
assert '[ -f abcd-efgh ]'
assert '[ -f abcd ]'

assert-equal 'default_val' '`cat all`'
assert-equal 'default2_val' '`cat abcd`'
assert-equal '' '`cat abcd-efgh`'
assert-equal 'outer' '`cat scoped`'
assert-equal 'inner' '`cat inner`'
assert-equal 'aye' '`cat check-pwd`'

default=changed default2=changed2 numake
assert-equal 'changed' '`cat all`'
assert-equal 'changed2' '`cat abcd`'
assert-equal '' '`cat abcd-efgh`'
assert-equal 'inner' '`cat inner`'
assert-equal 'aye' '`cat check-pwd`'
