#!/bin/sh -e

# NUMAKE_START_DIR is always the same as the directory where numake is called
# NUMAKE_ROOT_DIR is the first directory that contains a .numake directory
# when searching upward from the current directory

EXPECTED_START_DIR=$(pwd) numake check-start-dir
EXPECTED_ROOT_DIR=$(pwd) numake check-root-dir

mkdir subdir
cd subdir

assert-fail numake

EXPECTED_START_DIR=$(pwd) numake ../check-start-dir
EXPECTED_ROOT_DIR=$(readlink -f ../) numake ../check-root-dir

# Make subdir a new numake project
numake --init

# This will fail because rules.nmk cannot be found
EXPECTED_START_DIR=$(pwd) assert-fail numake ../check-start-dir
EXPECTED_ROOT_DIR=$(pwd) assert-fail numake ../check-root-dir

cp ../rules.nmk .
EXPECTED_START_DIR=$(pwd) numake check-start-dir
EXPECTED_ROOT_DIR=$(pwd) numake check-root-dir
