#!/bin/bash -e

# Ensure that all required scripts are present and function as expected

which assert > /dev/null
which assert-equal > /dev/null
which assert-fail > /dev/null
which numake > /dev/null

assert '[ 1 = 1 ]'
assert 'assert true'
assert-fail '[ 1 != 1 ]'
assert-fail 'assert false'
assert-fail 'false'
assert 'assert-fail false'
assert-equal '1' '1'
assert-fail 'assert-equal 1 2'
