#!/bin/bash -e

# Moving a project to a different directory will not trigger rebuild

export test_dir=$(readlink -f $(pwd))

pushd old-dir
numake
rm rebuilt
popd

mv old-dir new-dir

pushd new-dir
numake
assert '[ ! -f rebuilt ]'
popd

mkdir subdir
mv new-dir subdir

cd subdir/new-dir
numake
assert '[ ! -f rebuilt ]'
