#!/bin/sh -e

# Regular dependencies and order-only dependencies are exposed as local
# variables

numake

assert-equal '"regular1 regular2"' '`cat deps`'
assert-equal '"order3 order4"' '`cat order_deps`'
