#!/bin/sh -e

# Verify that all targets, even live ones are only visited and rebuilt once
# per top-level invocation of numake

rm -rf log
numake

assert 'diff log1 log'

rm -rf log a b c

numake

assert 'diff log1 log'
